DFLAGS = -DLEDA_STL_ITERATORS
 
LROOT   = ../../../..
UNIXLIB = -lleda $(XLIB) -lm
DOSLIB  = ..\\..\\..\\leda.lib $(XLIB)
DOSLIB1 = ..\\..\\..\\libGeoW.lib
 
WINDOW_APP = 1

include ../../../Make.pro

