#

all:
	if [ -d core/misc    ]; then cd core/misc;    $(MAKE); fi
	if [ -d core/dict    ]; then cd core/dict;    $(MAKE); fi
	if [ -d numbers      ]; then cd numbers;      $(MAKE); fi
	if [ -d coding       ]; then cd coding;     $(MAKE); fi
	if [ -d graph/misc   ]; then cd graph/misc;   $(MAKE); fi
	if [ -d graph/flow   ]; then cd graph/flow;   $(MAKE); fi
	if [ -d geo/d2_geo   ]; then cd geo/d2_geo;   $(MAKE); fi
	if [ -d geo/real_geo ]; then cd geo/real_geo; $(MAKE); fi
	if [ -d graphics/window    ]; then cd graphics/window;    $(MAKE); fi
	if [ -d graphics/graphdraw ]; then cd graphics/graphdraw; $(MAKE); fi
	if [ -d graphics/graphwin  ]; then cd graphics/graphwin;  $(MAKE); fi


clean:
	if [ -d core/misc    ]; then cd core/misc;    $(MAKE) clean; fi
	if [ -d core/dict    ]; then cd core/dict;    $(MAKE) clean; fi
	if [ -d numbers      ]; then cd numbers;      $(MAKE) clean; fi
	if [ -d coding       ]; then cd coding;       $(MAKE) clean; fi
	if [ -d graph/misc   ]; then cd graph/misc;   $(MAKE) clean; fi
	if [ -d graph/flow   ]; then cd graph/flow;   $(MAKE) clean; fi
	if [ -d geo/d2_geo   ]; then cd geo/d2_geo;   $(MAKE) clean; fi
	if [ -d geo/real_geo ]; then cd geo/real_geo; $(MAKE) clean; fi
	if [ -d graphics/window    ];then cd graphics/window;   $(MAKE) clean;fi
	if [ -d graphics/graphdraw ];then cd graphics/graphdraw;$(MAKE) clean;fi
	if [ -d graphics/graphwin  ];then cd graphics/graphwin; $(MAKE) clean;fi


del:
	if [ -d core/misc    ]; then cd core/misc;    $(MAKE) del; fi
	if [ -d core/dict    ]; then cd core/dict;    $(MAKE) del; fi
	if [ -d numbers      ]; then cd numbers;      $(MAKE) del; fi
	if [ -d coding       ]; then cd coding;       $(MAKE) del; fi
	if [ -d graph/misc   ]; then cd graph/misc;   $(MAKE) del; fi
	if [ -d graph/flow   ]; then cd graph/flow;   $(MAKE) del; fi
	if [ -d geo/d2_geo   ]; then cd geo/d2_geo;   $(MAKE) del; fi
	if [ -d geo/real_geo ]; then cd geo/real_geo; $(MAKE) del; fi
	if [ -d graphics/window    ];then cd graphics/window;    $(MAKE) del;fi
	if [ -d graphics/graphdraw ];then cd graphics/graphdraw; $(MAKE) del;fi
	if [ -d graphics/graphwin  ];then cd graphics/graphwin;  $(MAKE) del;fi
	if [ -d system/socket ];then cd system/socket; $(MAKE) del;fi
	if [ -d system/thread ];then cd system/thread; $(MAKE) del;fi


